return {
  "m4xshen/hardtime.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  opts = {
    disable_mouse = false,

    disabled_filetypes = {
      "grug-far",
      "NvimTree",
      "TelescopePrompt",
      "aerial",
      "alpha",
      "checkhealth",
      "dapui*",
      "Diffview*",
      "Dressing*",
      "help",
      "httpResult",
      "lazy",
      "lspinfo",
      "Neogit*",
      "mason",
      "neotest%-summary",
      "minifiles",
      "neo%-tree*",
      "netrw",
      "noice",
      "notify",
      "prompt",
      "qf",
      "query",
      "oil",
      "undotree",
      "trouble",
      "Trouble",
      "fugitive",
      "dbui",
      "copilot-chat",
    },
  },
  command = "Hardtime",
  event = "BufEnter",
  -- keys = {
  --   { "n", "j", "<cmd>Hardtime<CR>", desc = "Hardtime" },
  --   { "n", "k", "<cmd>Hardtime<CR>", desc = "Hardtime" },
  --   { "n", "gj", "<cmd>Hardtime<CR>", desc = "Hardtime" },
  --   { "n", "gk", "<cmd>Hardtime<CR>", desc = "Hardtime" },
  -- },
}
