return {}
-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     capabilities = {
--       textDocument = {
--         foldingRange = {
--           dynamicRegistration = false,
--           lineFoldingOnly = true,
--         },
--       },
--     },
--   },
-- }
